### ISSUE TITLE
run test_scene_3d.tscn have error

### ISSUE THREAD

**Issue by lokwingfai** [Giwayume/godot-svg#4]
Run res://tests/w3c_1.1_test_suite/test_scene_3d.tscn
Have error at
Line 595
"Invalid type in function 'generate_uv_at_point' in base 'GDScript'.Cannot convert argument 2 form Vector3 to Vector2."

Godot 3.5
macOS Sonoma 14.11

**Comment by Giwayume** [comment]
I never got 3D working.

**Comment by Giwayume** [comment]
OK, I got it working somewhat in the 4.3 branch. Note, as of writing, Godot 4.3 is still in beta, and 4.3 is required. The game's anti-aliasing setting impacts the shapes.

https://github.com/Giwayume/godot-svg/tree/4.3

![image](https://github.com/Giwayume/godot-svg/assets/4075314/10d3d4fe-10b1-491c-9eb0-377ca82e1c14)

**I do not recommend using this in your game**.

There's a lot of parts of the SVG spec that can't be supported in 3D. I'm also having difficulty getting the depth sorting working consistently, since Godot generally has bad options for sorting transparent objects.

Until Godot provides better sorting options, or I figure out some hacks, I'm going to consider SVG3D a pre-alpha node that could break without notice on any release. The focus of this library will primarily be getting SVG2D and SVGRect working as close to the SVG spec as possible.
